from __future__ import annotations

from dataclasses import dataclass

PRODUCT_IMAGE_BASE_URL = (
    "https://raw.githubusercontent.com/notcoinsapourt-web/Riva/main/assets/products-v3"
)
PRODUCT_IMAGE_VERSION = "20260901-luxury-v3"


@dataclass(frozen=True, slots=True)
class SeedCategory:
    name: str
    description: str
    emoji: str
    sort_order: int
    card_color: tuple[str, str]


@dataclass(frozen=True, slots=True)
class SeedProduct:
    category: str
    name: str
    card_title: str
    description: str
    price: int
    input_prompt: str
    emoji: str
    image_slug: str
    sort_order: int

    @property
    def photo_url(self) -> str:
        return f"{PRODUCT_IMAGE_BASE_URL}/{self.image_slug}.jpg?v={PRODUCT_IMAGE_VERSION}"


DEFAULT_CATEGORIES: tuple[SeedCategory, ...] = (
    SeedCategory(
        "خدمات تلگرام",
        "ممبر، بازدید، ری‌اکشن و خدمات رشد کانال و گروه تلگرام",
        "✈️",
        10,
        ("#24A1DE", "#1769AA"),
    ),
    SeedCategory(
        "خدمات اینستاگرام",
        "فالوور، لایک، ویو، سیو، اشتراک‌گذاری و تعامل پیج",
        "📸",
        20,
        ("#833AB4", "#FD1D1D"),
    ),
    SeedCategory(
        "خدمات تیک‌تاک",
        "فالوور، لایک، ویو، کامنت، سیو و اشتراک‌گذاری TikTok",
        "🎵",
        25,
        ("#111111", "#25F4EE"),
    ),
    SeedCategory(
        "خدمات یوتیوب",
        "سابسکرایب، بازدید، لایک، کامنت و خدمات Shorts",
        "▶️",
        27,
        ("#FF0000", "#8B0000"),
    ),
    SeedCategory(
        "اشتراک هوش مصنوعی",
        "اشتراک ابزارهای متنی، تصویری، ویدیویی، صوتی و برنامه‌نویسی AI",
        "🤖",
        30,
        ("#10A37F", "#334155"),
    ),
    SeedCategory(
        "سایر محصولات دیجیتال",
        "اشتراک‌های پرمیوم، موسیقی، ویدیو، طراحی و ابزارهای کاربردی",
        "💎",
        40,
        ("#7C3AED", "#2563EB"),
    ),
    SeedCategory(
        "سایر شبکه‌های اجتماعی",
        "خدمات تردز، ایکس، دیسکورد، توییچ و لینکدین",
        "🌐",
        50,
        ("#0F172A", "#475569"),
    ),
)


SOCIAL_INPUT = "لینک عمومی پیج یا پست را ارسال کنید. رمز عبور لازم نیست."
CHANNEL_INPUT = "لینک عمومی کانال، گروه یا پست را ارسال کنید. رمز عبور لازم نیست."
AI_INPUT = (
    "نام پلن و ایمیل حساب را ارسال کنید. برای امنیت، رمز عبور را داخل ربات نفرستید؛ "
    "هماهنگی فعال‌سازی از طریق پشتیبانی انجام می‌شود."
)
SUBSCRIPTION_INPUT = (
    "ایمیل یا نام کاربری حساب و پلن موردنظر را ارسال کنید. رمز عبور را داخل ربات نفرستید."
)


DEFAULT_PRODUCTS: tuple[SeedProduct, ...] = (
    # Instagram
    SeedProduct(
        "خدمات اینستاگرام",
        "۱۰۰۰ فالوور اقتصادی اینستاگرام",
        "1K INSTAGRAM\nFOLLOWERS",
        "بسته اقتصادی افزایش فالوور برای پیج‌های عمومی؛ شروع سریع و مناسب اعتبار اولیه پیج.",
        149_000,
        SOCIAL_INPUT,
        "👥",
        "instagram-followers-1k-economy",
        10,
    ),
    SeedProduct(
        "خدمات اینستاگرام",
        "۱۰۰۰ فالوور کیفیت بالا اینستاگرام",
        "1K INSTAGRAM\nPREMIUM FOLLOWERS",
        "فالوور با پروفایل کامل‌تر و کیفیت بالاتر؛ مناسب پیج‌های فروشگاهی و کاری.",
        329_000,
        SOCIAL_INPUT,
        "⭐",
        "instagram-followers-1k-premium",
        20,
    ),
    SeedProduct(
        "خدمات اینستاگرام",
        "۱۰۰۰ لایک اقتصادی اینستاگرام",
        "1K INSTAGRAM\nLIKES",
        "لایک سریع برای پست یا ریلز عمومی؛ مناسب افزایش نمایش اولیه محتوا.",
        29_000,
        SOCIAL_INPUT,
        "❤️",
        "instagram-likes-1k",
        30,
    ),
    SeedProduct(
        "خدمات اینستاگرام",
        "۱۰۰۰ لایک ایرانی اینستاگرام",
        "1K IRANIAN\nLIKES",
        "لایک با پروفایل‌های فارسی و ایرانی برای پست یا ریلز عمومی.",
        69_000,
        SOCIAL_INPUT,
        "🇮🇷",
        "instagram-likes-1k-iranian",
        40,
    ),
    SeedProduct(
        "خدمات اینستاگرام",
        "۱۰ هزار ویو ریلز اینستاگرام",
        "10K REELS\nVIEWS",
        "ده هزار بازدید برای یک ریلز عمومی با شروع سریع و تحویل مرحله‌ای.",
        49_000,
        SOCIAL_INPUT,
        "🎬",
        "instagram-reels-views-10k",
        50,
    ),
    SeedProduct(
        "خدمات اینستاگرام",
        "۵۰۰۰ ویو استوری اینستاگرام",
        "5K STORY\nVIEWS",
        "افزایش بازدید یک استوری فعال؛ لینک استوری باید تا پایان انجام سفارش معتبر باشد.",
        89_000,
        SOCIAL_INPUT,
        "👁",
        "instagram-story-views-5k",
        60,
    ),
    SeedProduct(
        "خدمات اینستاگرام",
        "۱۰۰ کامنت دلخواه اینستاگرام",
        "100 CUSTOM\nCOMMENTS",
        "کامنت با متن‌های پیشنهادی شما برای یک پست عمومی؛ متن‌ها پس از سفارش دریافت می‌شوند.",
        149_000,
        "لینک پست و متن کامنت‌های دلخواه را ارسال کنید. رمز عبور لازم نیست.",
        "💬",
        "instagram-comments-100",
        70,
    ),
    SeedProduct(
        "خدمات اینستاگرام",
        "۱۰۰۰ ذخیره پست اینستاگرام",
        "1K INSTAGRAM\nSAVES",
        "افزایش تعداد ذخیره برای پست یا ریلز عمومی؛ مناسب تقویت سیگنال تعامل.",
        59_000,
        SOCIAL_INPUT,
        "🔖",
        "instagram-saves-1k",
        80,
    ),
    SeedProduct(
        "خدمات اینستاگرام",
        "۱۰۰۰ اشتراک‌گذاری اینستاگرام",
        "1K INSTAGRAM\nSHARES",
        "افزایش Share برای پست یا ریلز عمومی با تحویل کنترل‌شده.",
        59_000,
        SOCIAL_INPUT,
        "📤",
        "instagram-shares-1k",
        90,
    ),
    SeedProduct(
        "خدمات اینستاگرام",
        "پکیج شروع پیج اینستاگرام",
        "INSTAGRAM\nSTARTER PACK",
        "۱۰۰۰ فالوور اقتصادی، ۲۰۰۰ لایک و ۱۰ هزار ویو ریلز برای شروع یک پیج عمومی.",
        249_000,
        "لینک پیج و لینک یک ریلز را ارسال کنید. رمز عبور لازم نیست.",
        "🚀",
        "instagram-starter-pack",
        100,
    ),
    # Telegram
    SeedProduct(
        "خدمات تلگرام",
        "۱۰۰۰ ممبر اقتصادی تلگرام",
        "1K TELEGRAM\nMEMBERS",
        "افزایش ممبر برای کانال یا گروه عمومی؛ گزینه اقتصادی برای شروع و تکمیل ظاهر کانال.",
        39_000,
        CHANNEL_INPUT,
        "👥",
        "telegram-members-1k-economy",
        10,
    ),
    SeedProduct(
        "خدمات تلگرام",
        "۱۰۰۰ ممبر کیفیت بالا تلگرام",
        "1K TELEGRAM\nPREMIUM MEMBERS",
        "ممبر با کیفیت بالاتر و تحویل کنترل‌شده برای کانال و گروه عمومی.",
        149_000,
        CHANNEL_INPUT,
        "⭐",
        "telegram-members-1k-premium",
        20,
    ),
    SeedProduct(
        "خدمات تلگرام",
        "۱۰۰۰ ممبر ایرانی تلگرام",
        "1K IRANIAN\nMEMBERS",
        "بسته ممبر با پروفایل‌های فارسی و ایرانی برای کانال یا گروه عمومی.",
        299_000,
        CHANNEL_INPUT,
        "🇮🇷",
        "telegram-members-1k-iranian",
        30,
    ),
    SeedProduct(
        "خدمات تلگرام",
        "۱۰ هزار بازدید پست تلگرام",
        "10K TELEGRAM\nPOST VIEWS",
        "ده هزار بازدید برای یک پست عمومی کانال با شروع سریع.",
        29_000,
        CHANNEL_INPUT,
        "👁",
        "telegram-views-10k",
        40,
    ),
    SeedProduct(
        "خدمات تلگرام",
        "بازدید ۵ پست آینده تلگرام",
        "5 FUTURE POSTS\nVIEWS",
        "ثبت خودکار بازدید روی پنج پست بعدی کانال؛ برای کانال عمومی.",
        79_000,
        CHANNEL_INPUT,
        "🔁",
        "telegram-future-posts-5",
        50,
    ),
    SeedProduct(
        "خدمات تلگرام",
        "۱۰۰۰ ری‌اکشن مثبت تلگرام",
        "1K TELEGRAM\nREACTIONS",
        "ترکیب ری‌اکشن‌های مثبت برای یک پست عمومی تلگرام.",
        99_000,
        CHANNEL_INPUT,
        "🔥",
        "telegram-reactions-1k",
        60,
    ),
    SeedProduct(
        "خدمات تلگرام",
        "۱۰۰۰ رأی نظرسنجی تلگرام",
        "1K TELEGRAM\nPOLL VOTES",
        "افزایش رأی یک گزینه در نظرسنجی عمومی تلگرام.",
        189_000,
        "لینک نظرسنجی و شماره یا متن گزینه موردنظر را ارسال کنید.",
        "🗳",
        "telegram-poll-votes-1k",
        70,
    ),
    SeedProduct(
        "خدمات تلگرام",
        "۱۰۰ اشتراک‌گذاری پست تلگرام",
        "100 TELEGRAM\nSHARES",
        "افزایش Share یک پست عمومی کانال برای گسترده‌تر شدن توزیع محتوا.",
        49_000,
        CHANNEL_INPUT,
        "📤",
        "telegram-shares-100",
        80,
    ),
    SeedProduct(
        "خدمات تلگرام",
        "پکیج شروع کانال تلگرام",
        "TELEGRAM\nSTARTER PACK",
        "۱۰۰۰ ممبر اقتصادی، ۱۰ هزار ویو و ۵۰۰ ری‌اکشن برای شروع کانال عمومی.",
        149_000,
        CHANNEL_INPUT,
        "🚀",
        "telegram-starter-pack",
        90,
    ),
    # TikTok
    SeedProduct(
        "خدمات تیک‌تاک",
        "۱۰۰۰ فالوور اقتصادی تیک‌تاک",
        "1K TIKTOK\nFOLLOWERS",
        "بسته اقتصادی افزایش فالوور برای پروفایل عمومی TikTok.",
        129_000,
        SOCIAL_INPUT,
        "👥",
        "tiktok-followers-1k-economy",
        10,
    ),
    SeedProduct(
        "خدمات تیک‌تاک",
        "۱۰۰۰ فالوور کیفیت بالا تیک‌تاک",
        "1K TIKTOK\nPREMIUM FOLLOWERS",
        "فالوور با کیفیت بالاتر برای پروفایل عمومی و تحویل کنترل‌شده.",
        299_000,
        SOCIAL_INPUT,
        "⭐",
        "tiktok-followers-1k-premium",
        20,
    ),
    SeedProduct(
        "خدمات تیک‌تاک",
        "۱۰ هزار ویو تیک‌تاک",
        "10K TIKTOK\nVIEWS",
        "ده هزار بازدید برای یک ویدیوی عمومی TikTok با شروع سریع.",
        49_000,
        SOCIAL_INPUT,
        "👁",
        "tiktok-views-10k",
        30,
    ),
    SeedProduct(
        "خدمات تیک‌تاک",
        "۱۰۰۰ لایک تیک‌تاک",
        "1K TIKTOK\nLIKES",
        "هزار لایک برای یک ویدیوی عمومی TikTok.",
        49_000,
        SOCIAL_INPUT,
        "❤️",
        "tiktok-likes-1k",
        40,
    ),
    SeedProduct(
        "خدمات تیک‌تاک",
        "۱۰۰ کامنت دلخواه تیک‌تاک",
        "100 TIKTOK\nCOMMENTS",
        "کامنت‌های دلخواه برای یک ویدیوی عمومی؛ متن‌ها توسط شما تعیین می‌شوند.",
        139_000,
        "لینک ویدیو و متن کامنت‌های دلخواه را ارسال کنید.",
        "💬",
        "tiktok-comments-100",
        50,
    ),
    SeedProduct(
        "خدمات تیک‌تاک",
        "۱۰۰۰ اشتراک‌گذاری تیک‌تاک",
        "1K TIKTOK\nSHARES",
        "افزایش Share یک ویدیوی عمومی TikTok.",
        59_000,
        SOCIAL_INPUT,
        "📤",
        "tiktok-shares-1k",
        60,
    ),
    SeedProduct(
        "خدمات تیک‌تاک",
        "۱۰۰۰ ذخیره ویدیو تیک‌تاک",
        "1K TIKTOK\nSAVES",
        "افزایش ذخیره برای یک ویدیوی عمومی TikTok.",
        59_000,
        SOCIAL_INPUT,
        "🔖",
        "tiktok-saves-1k",
        70,
    ),
    SeedProduct(
        "خدمات تیک‌تاک",
        "پکیج وایرال تیک‌تاک",
        "TIKTOK\nVIRAL PACK",
        "۱۰ هزار ویو، ۲۰۰۰ لایک و ۵۰۰ اشتراک‌گذاری برای یک ویدیوی عمومی.",
        149_000,
        SOCIAL_INPUT,
        "🚀",
        "tiktok-viral-pack",
        80,
    ),
    # YouTube
    SeedProduct(
        "خدمات یوتیوب",
        "۱۰۰ سابسکرایب اقتصادی یوتیوب",
        "100 YOUTUBE\nSUBSCRIBERS",
        "صد سابسکرایب اقتصادی برای کانال عمومی یوتیوب؛ مناسب شروع کانال.",
        79_000,
        SOCIAL_INPUT,
        "🔔",
        "youtube-subscribers-100-economy",
        10,
    ),
    SeedProduct(
        "خدمات یوتیوب",
        "۱۰۰ سابسکرایب کیفیت بالا یوتیوب",
        "100 PREMIUM\nSUBSCRIBERS",
        "صد سابسکرایب با کیفیت بالاتر و تحویل آهسته‌تر برای کانال عمومی.",
        449_000,
        SOCIAL_INPUT,
        "⭐",
        "youtube-subscribers-100-premium",
        20,
    ),
    SeedProduct(
        "خدمات یوتیوب",
        "۱۰۰۰ ویو اقتصادی یوتیوب",
        "1K YOUTUBE\nVIEWS",
        "هزار بازدید اقتصادی برای یک ویدیوی عمومی یوتیوب.",
        199_000,
        SOCIAL_INPUT,
        "👁",
        "youtube-views-1k-economy",
        30,
    ),
    SeedProduct(
        "خدمات یوتیوب",
        "۱۰۰۰ ویو با زمان تماشا یوتیوب",
        "1K WATCH-TIME\nVIEWS",
        "بازدید با ماندگاری بیشتر برای ویدیوی عمومی؛ مناسب تقویت Watch Time محتوا.",
        549_000,
        SOCIAL_INPUT,
        "⏱",
        "youtube-watchtime-views-1k",
        40,
    ),
    SeedProduct(
        "خدمات یوتیوب",
        "۱۰۰۰ لایک یوتیوب",
        "1K YOUTUBE\nLIKES",
        "هزار لایک برای یک ویدیوی عمومی یوتیوب.",
        149_000,
        SOCIAL_INPUT,
        "👍",
        "youtube-likes-1k",
        50,
    ),
    SeedProduct(
        "خدمات یوتیوب",
        "۱۰۰ کامنت دلخواه یوتیوب",
        "100 YOUTUBE\nCOMMENTS",
        "کامنت‌های دلخواه برای یک ویدیوی عمومی؛ متن‌ها توسط شما مشخص می‌شوند.",
        299_000,
        "لینک ویدیو و متن کامنت‌های دلخواه را ارسال کنید.",
        "💬",
        "youtube-comments-100",
        60,
    ),
    SeedProduct(
        "خدمات یوتیوب",
        "۱۰ هزار ویو YouTube Shorts",
        "10K SHORTS\nVIEWS",
        "ده هزار بازدید برای یک ویدیوی عمومی Shorts.",
        149_000,
        SOCIAL_INPUT,
        "🎬",
        "youtube-shorts-views-10k",
        70,
    ),
    SeedProduct(
        "خدمات یوتیوب",
        "پکیج شروع کانال یوتیوب",
        "YOUTUBE\nSTARTER PACK",
        "۱۰۰ سابسکرایب اقتصادی، ۱۰۰۰ ویو و ۵۰۰ لایک برای شروع کانال عمومی.",
        349_000,
        "لینک کانال و لینک یک ویدیوی عمومی را ارسال کنید.",
        "🚀",
        "youtube-starter-pack",
        80,
    ),
    # AI subscriptions
    SeedProduct(
        "اشتراک هوش مصنوعی",
        "ChatGPT Plus اشتراکی یک‌ماهه",
        "CHATGPT PLUS\nSHARED • 1 MONTH",
        "دسترسی یک‌ماهه اقتصادی تحت وب؛ مناسب استفاده روزمره، تولید محتوا و تحلیل.",
        699_000,
        AI_INPUT,
        "🧠",
        "ai-chatgpt-plus-shared",
        10,
    ),
    SeedProduct(
        "اشتراک هوش مصنوعی",
        "ChatGPT Plus اختصاصی یک‌ماهه",
        "CHATGPT PLUS\nPERSONAL • 1 MONTH",
        "فعال‌سازی قانونی یک‌ماهه روی حساب شخصی؛ مناسب استفاده حرفه‌ای در وب و اپ.",
        3_790_000,
        AI_INPUT,
        "🧠",
        "ai-chatgpt-plus-personal",
        20,
    ),
    SeedProduct(
        "اشتراک هوش مصنوعی",
        "Claude Pro اختصاصی یک‌ماهه",
        "CLAUDE PRO\n1 MONTH",
        "اشتراک اختصاصی Claude Pro برای تحلیل متن، کدنویسی و کار با فایل‌های طولانی.",
        4_990_000,
        AI_INPUT,
        "🟠",
        "ai-claude-pro",
        30,
    ),
    SeedProduct(
        "اشتراک هوش مصنوعی",
        "Gemini Advanced یک‌ماهه",
        "GEMINI ADVANCED\n1 MONTH",
        "اشتراک پیشرفته گوگل برای متن، تصویر، فایل و قابلیت‌های هوش مصنوعی اکوسیستم Google.",
        1_490_000,
        AI_INPUT,
        "✨",
        "ai-gemini-advanced",
        40,
    ),
    SeedProduct(
        "اشتراک هوش مصنوعی",
        "Perplexity Pro یک‌ماهه",
        "PERPLEXITY PRO\n1 MONTH",
        "موتور پژوهش هوشمند با جست‌وجوی پیشرفته، منابع و دسترسی به مدل‌های حرفه‌ای.",
        5_190_000,
        AI_INPUT,
        "🔎",
        "ai-perplexity-pro",
        50,
    ),
    SeedProduct(
        "اشتراک هوش مصنوعی",
        "Midjourney Basic یک‌ماهه",
        "MIDJOURNEY BASIC\n1 MONTH",
        "پلن پایه تولید تصویر برای طراحی، تبلیغات، کانسپت آرت و محتوای شبکه‌های اجتماعی.",
        2_690_000,
        AI_INPUT,
        "🎨",
        "ai-midjourney-basic",
        60,
    ),
    SeedProduct(
        "اشتراک هوش مصنوعی",
        "Suno AI Pro یک‌ماهه",
        "SUNO AI PRO\n1 MONTH",
        "اشتراک تولید موسیقی و آهنگ با هوش مصنوعی برای پروژه‌های محتوایی.",
        4_190_000,
        AI_INPUT,
        "🎧",
        "ai-suno-pro",
        70,
    ),
    SeedProduct(
        "اشتراک هوش مصنوعی",
        "ElevenLabs Creator یک‌ماهه",
        "ELEVENLABS\nCREATOR • 1 MONTH",
        "تولید و تبدیل صدای حرفه‌ای برای دوبله، پادکست و محتوای ویدیویی.",
        3_290_000,
        AI_INPUT,
        "🎙",
        "ai-elevenlabs-creator",
        80,
    ),
    SeedProduct(
        "اشتراک هوش مصنوعی",
        "Cursor Pro یک‌ماهه",
        "CURSOR PRO\n1 MONTH",
        "ویرایشگر برنامه‌نویسی هوشمند با تکمیل کد، چت پروژه و ابزارهای Agent.",
        3_990_000,
        AI_INPUT,
        "💻",
        "ai-cursor-pro",
        90,
    ),
    SeedProduct(
        "اشتراک هوش مصنوعی",
        "Google Flow یک‌ماهه",
        "GOOGLE FLOW\n1 MONTH",
        "ابزار هوش مصنوعی گوگل برای ساخت ویدیو و تولید محتوای تصویری حرفه‌ای.",
        2_290_000,
        AI_INPUT,
        "🎞",
        "ai-google-flow",
        100,
    ),
    SeedProduct(
        "اشتراک هوش مصنوعی",
        "Canva Pro یک‌ماهه",
        "CANVA PRO\n1 MONTH",
        "دسترسی به قالب‌ها، ابزارهای طراحی و قابلیت‌های هوش مصنوعی Canva Pro.",
        449_000,
        AI_INPUT,
        "🖌",
        "ai-canva-pro",
        110,
    ),
    SeedProduct(
        "اشتراک هوش مصنوعی",
        "CapCut Pro یک‌ماهه",
        "CAPCUT PRO\n1 MONTH",
        "ویرایش حرفه‌ای ویدیو، قالب‌های پرمیوم، زیرنویس خودکار و ابزارهای AI.",
        449_000,
        AI_INPUT,
        "✂️",
        "ai-capcut-pro",
        120,
    ),
    # Digital subscriptions
    SeedProduct(
        "سایر محصولات دیجیتال",
        "تلگرام پرمیوم سه‌ماهه",
        "TELEGRAM PREMIUM\n3 MONTHS",
        "فعال‌سازی رسمی سه‌ماهه به‌صورت Gift روی حساب واجد شرایط؛ بدون دریافت رمز عبور.",
        3_190_000,
        "نام کاربری تلگرام و کشور شماره را ارسال کنید. رمز عبور لازم نیست.",
        "✈️",
        "digital-telegram-premium-3m",
        10,
    ),
    SeedProduct(
        "سایر محصولات دیجیتال",
        "تلگرام پرمیوم شش‌ماهه",
        "TELEGRAM PREMIUM\n6 MONTHS",
        "فعال‌سازی رسمی شش‌ماهه به‌صورت Gift روی حساب واجد شرایط.",
        4_090_000,
        "نام کاربری تلگرام و کشور شماره را ارسال کنید. رمز عبور لازم نیست.",
        "✈️",
        "digital-telegram-premium-6m",
        20,
    ),
    SeedProduct(
        "سایر محصولات دیجیتال",
        "تلگرام پرمیوم یک‌ساله",
        "TELEGRAM PREMIUM\n12 MONTHS",
        "فعال‌سازی رسمی یک‌ساله به‌صورت Gift روی حساب واجد شرایط.",
        7_190_000,
        "نام کاربری تلگرام و کشور شماره را ارسال کنید. رمز عبور لازم نیست.",
        "✈️",
        "digital-telegram-premium-12m",
        30,
    ),
    SeedProduct(
        "سایر محصولات دیجیتال",
        "Spotify Premium یک‌ماهه",
        "SPOTIFY PREMIUM\n1 MONTH",
        "اشتراک یک‌ماهه موسیقی بدون تبلیغات، پخش آفلاین و کیفیت بالاتر.",
        499_000,
        SUBSCRIPTION_INPUT,
        "🎧",
        "digital-spotify-premium",
        40,
    ),
    SeedProduct(
        "سایر محصولات دیجیتال",
        "YouTube Premium یک‌ماهه",
        "YOUTUBE PREMIUM\n1 MONTH",
        "تماشای بدون تبلیغ، پخش پس‌زمینه، دانلود آفلاین و YouTube Music.",
        499_000,
        SUBSCRIPTION_INPUT,
        "▶️",
        "digital-youtube-premium",
        50,
    ),
    SeedProduct(
        "سایر محصولات دیجیتال",
        "Apple Music یک‌ماهه",
        "APPLE MUSIC\n1 MONTH",
        "اشتراک یک‌ماهه Apple Music با دسترسی به کتابخانه موسیقی و پخش باکیفیت.",
        449_000,
        SUBSCRIPTION_INPUT,
        "🎵",
        "digital-apple-music",
        60,
    ),
    SeedProduct(
        "سایر محصولات دیجیتال",
        "SoundCloud Go+ یک‌ماهه",
        "SOUNDCLOUD GO+\n1 MONTH",
        "پخش بدون تبلیغ، دسترسی کامل‌تر و ذخیره آفلاین موسیقی.",
        299_000,
        SUBSCRIPTION_INPUT,
        "☁️",
        "digital-soundcloud-go",
        70,
    ),
    SeedProduct(
        "سایر محصولات دیجیتال",
        "Discord Nitro یک‌ماهه",
        "DISCORD NITRO\n1 MONTH",
        "اشتراک Nitro با ایموجی‌های بیشتر، آپلود بزرگ‌تر و امکانات پروفایل.",
        899_000,
        SUBSCRIPTION_INPUT,
        "🎮",
        "digital-discord-nitro",
        80,
    ),
    SeedProduct(
        "سایر محصولات دیجیتال",
        "Google One صد گیگ یک‌ساله",
        "GOOGLE ONE\n100GB • 1 YEAR",
        "صد گیگابایت فضای Google One برای Drive، Gmail و Photos به مدت یک سال.",
        1_790_000,
        SUBSCRIPTION_INPUT,
        "☁️",
        "digital-google-one-100gb",
        90,
    ),
    SeedProduct(
        "سایر محصولات دیجیتال",
        "Microsoft 365 یک‌ساله",
        "MICROSOFT 365\n1 YEAR",
        "دسترسی یک‌ساله به Word، Excel، PowerPoint و فضای ابری مطابق پلن سفارش.",
        1_490_000,
        SUBSCRIPTION_INPUT,
        "📊",
        "digital-microsoft-365",
        100,
    ),
    # Other social networks
    SeedProduct(
        "سایر شبکه‌های اجتماعی",
        "۱۰۰۰ فالوور تردز",
        "1K THREADS\nFOLLOWERS",
        "افزایش فالوور برای پروفایل عمومی Threads؛ بدون نیاز به رمز عبور.",
        299_000,
        SOCIAL_INPUT,
        "🧵",
        "social-threads-followers-1k",
        10,
    ),
    SeedProduct(
        "سایر شبکه‌های اجتماعی",
        "۱۰۰۰ لایک تردز",
        "1K THREADS\nLIKES",
        "هزار لایک برای یک پست عمومی Threads.",
        79_000,
        SOCIAL_INPUT,
        "❤️",
        "social-threads-likes-1k",
        20,
    ),
    SeedProduct(
        "سایر شبکه‌های اجتماعی",
        "۱۰۰۰ فالوور X",
        "1K X\nFOLLOWERS",
        "افزایش فالوور برای حساب عمومی X با تحویل مرحله‌ای.",
        349_000,
        SOCIAL_INPUT,
        "𝕏",
        "social-x-followers-1k",
        30,
    ),
    SeedProduct(
        "سایر شبکه‌های اجتماعی",
        "۱۰۰۰ لایک X",
        "1K X\nLIKES",
        "هزار لایک برای یک پست عمومی در X.",
        129_000,
        SOCIAL_INPUT,
        "❤️",
        "social-x-likes-1k",
        40,
    ),
    SeedProduct(
        "سایر شبکه‌های اجتماعی",
        "۱۰۰۰ ممبر Discord",
        "1K DISCORD\nMEMBERS",
        "افزایش عضو سرور Discord از طریق لینک دعوت معتبر و عمومی.",
        399_000,
        "لینک دعوت معتبر سرور Discord را ارسال کنید.",
        "🎮",
        "social-discord-members-1k",
        50,
    ),
    SeedProduct(
        "سایر شبکه‌های اجتماعی",
        "۱۰۰۰ فالوور Twitch",
        "1K TWITCH\nFOLLOWERS",
        "افزایش فالوور برای کانال عمومی Twitch.",
        449_000,
        SOCIAL_INPUT,
        "🟣",
        "social-twitch-followers-1k",
        60,
    ),
    SeedProduct(
        "سایر شبکه‌های اجتماعی",
        "۱۰۰۰ ویو Twitch",
        "1K TWITCH\nVIEWS",
        "هزار بازدید برای ویدیو یا محتوای عمومی Twitch.",
        199_000,
        SOCIAL_INPUT,
        "👁",
        "social-twitch-views-1k",
        70,
    ),
    SeedProduct(
        "سایر شبکه‌های اجتماعی",
        "۵۰۰ فالوور LinkedIn",
        "500 LINKEDIN\nFOLLOWERS",
        "افزایش فالوور برای صفحه عمومی شخصی یا شرکتی LinkedIn.",
        599_000,
        SOCIAL_INPUT,
        "💼",
        "social-linkedin-followers-500",
        80,
    ),
)
